name = "weather-mastra-ai-agent"
main = "dist/workers/index.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

# Workers 配置
[env.production]
name = "weather-mastra-ai-agent-prod"

[env.staging]
name = "weather-mastra-ai-agent-staging"

# 环境变量（需要通过 wrangler secret 设置）
[env.production.vars]
NODE_ENV = "production"
GRAPHQL_ENDPOINT = "https://weather-mastra-ai-agent-prod.your-subdomain.workers.dev/graphql"

[env.staging.vars]
NODE_ENV = "staging"
GRAPHQL_ENDPOINT = "https://weather-mastra-ai-agent-staging.your-subdomain.workers.dev/graphql"

# 需要通过 wrangler secret put 设置的敏感变量:
# wrangler secret put DEEPSEEK_API_KEY
# wrangler secret put OPENWEATHER_API_KEY

# KV 存储（可选，用于缓存会话数据）
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "your_kv_namespace_id"
# preview_id = "your_kv_preview_namespace_id"

# D1 数据库（可选，用于持久化存储）
# [[d1_databases]]
# binding = "DB"
# database_name = "weather-ai-db"
# database_id = "your_database_id"

# 定时任务（可选）
# [triggers]
# crons = ["0 */6 * * *"]  # 每6小时执行一次清理任务

# 资源限制
[limits]
cpu_ms = 50000
